name: "CI Java/Docker (reusable)"

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      gradle-arguments:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: eclipse-temurin:${{ inputs.java-version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            /home/gradle/.gradle/caches
            /home/gradle/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Run Gradle build
        run: ./gradlew ${{ inputs.gradle-arguments }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-test-results
          path: build/test-results

