name: "CI Java/Gradle (reusable)"

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      gradle-arguments:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Run Gradle
        run: ./gradlew ${{ inputs.gradle-arguments }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-test-results
          path: build/test-results

