name: Infrastructure Deploy Service

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: StratumTech/Realty-Management-System-Infrastructure/.github/workflows/ssh-deploy.yml@main
    with:
      remote-workdir: /home/stratumtech/Realty-Management-System-Infrastructure
      deploy-script: |
        docker-compose down &&
        docker-compose pull &&
        docker-compose up -d
    secrets:
      ssh-key-secret: ${{ secrets.SSH_PRIVATE_KEY }}
      ssh-host: ${{ secrets.SERVER_HOST }}
      ssh-user: ${{ secrets.SERVER_USER }}
      config-service-username: ${{ secrets.CONFIG_SERVICE_USERNAME }}
      config-service-password: ${{ secrets.CONFIG_SERVICE_PASSWORD }}
