name: "Deploy via SSH (reusable)"

on:
  workflow_call:
    inputs:
      ssh-key-secret:
        type: string
        required: true
      remote-workdir:
        type: string
        required: true
      deploy-script:
        type: string
        required: true
    secrets:
      ssh-host:
        required: true
      ssh-user:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets[ inputs.ssh-key-secret ] }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Copy files
        run: rsync -avz --delete ./ ${{ secrets['ssh-user'] }}@${{ secrets['ssh-host'] }}:${{ inputs.remote-workdir }}
        env:
          RSYNC_RSH: "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key"

      - name: Run deploy script
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets['ssh-user'] }}@${{ secrets['ssh-host'] }} \
            "cd ${{ inputs.remote-workdir }} && bash -c '${{ inputs.deploy-script }}'"

