name: "Deploy via SSH (reusable)"

on:
  workflow_call:
    inputs:
      remote-workdir:
        type: string
        required: true
      deploy-script:
        type: string
        required: true
    secrets:
      ssh-key-secret:
        required: true
      ssh-host:
        required: true
      ssh-user:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets[ 'ssh-key-secret' ] }}

      - name: Copy files to server
        run: |
          rsync -avz --delete ./ ${{ secrets['ssh-user'] }}@${{ secrets['ssh-host'] }}:${{ inputs.remote-workdir }}
        env:
          RSYNC_RSH: "ssh -o StrictHostKeyChecking=no"

      - name: Run deploy script on server
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets['ssh-user'] }}@${{ secrets['ssh-host'] }} \
            "cd ${{ inputs.remote-workdir }} && bash -c '${{ inputs.deploy-script }}'"
